# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import kyc_classifier_pb2 as kyc__classifier__pb2


class doc_classifier_serviceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetDocType = channel.unary_unary(
        '/doc_classifier_service/GetDocType',
        request_serializer=kyc__classifier__pb2.classifier_request.SerializeToString,
        response_deserializer=kyc__classifier__pb2.classifier_response.FromString,
        )


class doc_classifier_serviceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetDocType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_doc_classifier_serviceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetDocType': grpc.unary_unary_rpc_method_handler(
          servicer.GetDocType,
          request_deserializer=kyc__classifier__pb2.classifier_request.FromString,
          response_serializer=kyc__classifier__pb2.classifier_response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'doc_classifier_service', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
