import autogenerated_files.kyc_ocr_pb2 as kyc_ocr_pb2
import autogenerated_files.kyc_ocr_pb2_grpc as kyc_ocr_pb2_grpc


class OCR(kyc_ocr_pb2_grpc.ocr_serviceServicer):
    def GetOcrDetails(self, request, context):
        image_path = request.kyc_doc_path

        details= kyc_ocr_pb2.card_details(card_holder_name='Amruta', dob='26/01/93',
                                          gender='Female', relation_name='Bhaskar Patil',
                                          id_no='45983490224')
        return kyc_ocr_pb2.kyc_ocr_response(details=details, card_type='AADHAAR')
