import autogenerated_files.kyc_classifier_pb2 as kyc_classifier_pb2
import autogenerated_files.kyc_classifier_pb2_grpc as kyc_classifier_pb2_grpc


class Classifier(kyc_classifier_pb2_grpc.doc_classifier_serviceServicer):
    def GetDocType(self, request, context):
        doctype = 'PAN'
        return kyc_classifier_pb2.classifier_response(doc_path=doctype)

#
# def serve():
#     server = grpc.server(futures.ThreadPoolExecutor(max_workers=1))
#     kyc_classifier_pb2_grpc.add_doc_classifier_serviceServicer_to_server(Classifier(),server)
#     server.add_insecure_port('[::]:50057')
#     server.start()
