import time
import grpc
from concurrent import futures
from autogenerated_files import kyc_ocr_pb2_grpc \
    as kyc_ocr_pb2_grpc
from src import kyc_ocr_service as ocr



_ONE_DAY_IN_SECONDS = 0

def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=1))
    kyc_ocr_pb2_grpc.add_ocr_serviceServicer_to_server(ocr.OCR(),server)
    server.add_insecure_port('[::]:50057')
    server.start()
    try:
        while True:
            time.sleep(_ONE_DAY_IN_SECONDS)
    except KeyboardInterrupt:
        server.stop(0)


if __name__ == '__main__':
    print("Server started with port 50057 ")
    serve()
