# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rotation_model.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rotation_model.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14rotation_model.proto\"*\n\x0frotation_requet\x12\x17\n\x0fimage_to_rotate\x18\x01 \x01(\x0c\"*\n\x11rotation_response\x12\x15\n\rrotated_image\x18\x01 \x01(\x0c\x32I\n\x10rotation_service\x12\x35\n\x0bRotateImage\x12\x10.rotation_requet\x1a\x12.rotation_response\"\x00\x62\x06proto3'
)




_ROTATION_REQUET = _descriptor.Descriptor(
  name='rotation_requet',
  full_name='rotation_requet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_to_rotate', full_name='rotation_requet.image_to_rotate', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=66,
)


_ROTATION_RESPONSE = _descriptor.Descriptor(
  name='rotation_response',
  full_name='rotation_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rotated_image', full_name='rotation_response.rotated_image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['rotation_requet'] = _ROTATION_REQUET
DESCRIPTOR.message_types_by_name['rotation_response'] = _ROTATION_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

rotation_requet = _reflection.GeneratedProtocolMessageType('rotation_requet', (_message.Message,), {
  'DESCRIPTOR' : _ROTATION_REQUET,
  '__module__' : 'rotation_model_pb2'
  # @@protoc_insertion_point(class_scope:rotation_requet)
  })
_sym_db.RegisterMessage(rotation_requet)

rotation_response = _reflection.GeneratedProtocolMessageType('rotation_response', (_message.Message,), {
  'DESCRIPTOR' : _ROTATION_RESPONSE,
  '__module__' : 'rotation_model_pb2'
  # @@protoc_insertion_point(class_scope:rotation_response)
  })
_sym_db.RegisterMessage(rotation_response)



_ROTATION_SERVICE = _descriptor.ServiceDescriptor(
  name='rotation_service',
  full_name='rotation_service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=112,
  serialized_end=185,
  methods=[
  _descriptor.MethodDescriptor(
    name='RotateImage',
    full_name='rotation_service.RotateImage',
    index=0,
    containing_service=None,
    input_type=_ROTATION_REQUET,
    output_type=_ROTATION_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROTATION_SERVICE)

DESCRIPTOR.services_by_name['rotation_service'] = _ROTATION_SERVICE

# @@protoc_insertion_point(module_scope)
