# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyc_ocr.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kyc_ocr.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rkyc_ocr.proto\"\'\n\x0fkyc_ocr_request\x12\x14\n\x0ckyc_doc_path\x18\x01 \x01(\t\"k\n\x0c\x63\x61rd_details\x12\x18\n\x10\x63\x61rd_holder_name\x18\x01 \x01(\t\x12\x0b\n\x03\x64ob\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x15\n\rrelation_name\x18\x04 \x01(\t\x12\r\n\x05id_no\x18\x05 \x01(\t\"E\n\x10kyc_ocr_response\x12\x1e\n\x07\x64\x65tails\x18\x01 \x01(\x0b\x32\r.card_details\x12\x11\n\tcard_type\x18\x02 \x01(\t2E\n\x0bocr_service\x12\x36\n\rGetOcrDetails\x12\x10.kyc_ocr_request\x1a\x11.kyc_ocr_response\"\x00\x62\x06proto3'
)




_KYC_OCR_REQUEST = _descriptor.Descriptor(
  name='kyc_ocr_request',
  full_name='kyc_ocr_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kyc_doc_path', full_name='kyc_ocr_request.kyc_doc_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=56,
)


_CARD_DETAILS = _descriptor.Descriptor(
  name='card_details',
  full_name='card_details',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='card_holder_name', full_name='card_details.card_holder_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dob', full_name='card_details.dob', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='card_details.gender', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relation_name', full_name='card_details.relation_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_no', full_name='card_details.id_no', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=165,
)


_KYC_OCR_RESPONSE = _descriptor.Descriptor(
  name='kyc_ocr_response',
  full_name='kyc_ocr_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='details', full_name='kyc_ocr_response.details', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='card_type', full_name='kyc_ocr_response.card_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=236,
)

_KYC_OCR_RESPONSE.fields_by_name['details'].message_type = _CARD_DETAILS
DESCRIPTOR.message_types_by_name['kyc_ocr_request'] = _KYC_OCR_REQUEST
DESCRIPTOR.message_types_by_name['card_details'] = _CARD_DETAILS
DESCRIPTOR.message_types_by_name['kyc_ocr_response'] = _KYC_OCR_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

kyc_ocr_request = _reflection.GeneratedProtocolMessageType('kyc_ocr_request', (_message.Message,), {
  'DESCRIPTOR' : _KYC_OCR_REQUEST,
  '__module__' : 'kyc_ocr_pb2'
  # @@protoc_insertion_point(class_scope:kyc_ocr_request)
  })
_sym_db.RegisterMessage(kyc_ocr_request)

card_details = _reflection.GeneratedProtocolMessageType('card_details', (_message.Message,), {
  'DESCRIPTOR' : _CARD_DETAILS,
  '__module__' : 'kyc_ocr_pb2'
  # @@protoc_insertion_point(class_scope:card_details)
  })
_sym_db.RegisterMessage(card_details)

kyc_ocr_response = _reflection.GeneratedProtocolMessageType('kyc_ocr_response', (_message.Message,), {
  'DESCRIPTOR' : _KYC_OCR_RESPONSE,
  '__module__' : 'kyc_ocr_pb2'
  # @@protoc_insertion_point(class_scope:kyc_ocr_response)
  })
_sym_db.RegisterMessage(kyc_ocr_response)



_OCR_SERVICE = _descriptor.ServiceDescriptor(
  name='ocr_service',
  full_name='ocr_service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=238,
  serialized_end=307,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOcrDetails',
    full_name='ocr_service.GetOcrDetails',
    index=0,
    containing_service=None,
    input_type=_KYC_OCR_REQUEST,
    output_type=_KYC_OCR_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OCR_SERVICE)

DESCRIPTOR.services_by_name['ocr_service'] = _OCR_SERVICE

# @@protoc_insertion_point(module_scope)
