# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyc_classifier.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kyc_classifier.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14kyc_classifier.proto\"+\n\x12\x63lassifier_request\x12\x15\n\rdocument_path\x18\x01 \x01(\t\"\'\n\x13\x63lassifier_response\x12\x10\n\x08\x64oc_path\x18\x01 \x01(\t2S\n\x16\x64oc_classifier_service\x12\x39\n\nGetDocType\x12\x13.classifier_request\x1a\x14.classifier_response\"\x00\x62\x06proto3'
)




_CLASSIFIER_REQUEST = _descriptor.Descriptor(
  name='classifier_request',
  full_name='classifier_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='document_path', full_name='classifier_request.document_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=67,
)


_CLASSIFIER_RESPONSE = _descriptor.Descriptor(
  name='classifier_response',
  full_name='classifier_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='doc_path', full_name='classifier_response.doc_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['classifier_request'] = _CLASSIFIER_REQUEST
DESCRIPTOR.message_types_by_name['classifier_response'] = _CLASSIFIER_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

classifier_request = _reflection.GeneratedProtocolMessageType('classifier_request', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFIER_REQUEST,
  '__module__' : 'kyc_classifier_pb2'
  # @@protoc_insertion_point(class_scope:classifier_request)
  })
_sym_db.RegisterMessage(classifier_request)

classifier_response = _reflection.GeneratedProtocolMessageType('classifier_response', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFIER_RESPONSE,
  '__module__' : 'kyc_classifier_pb2'
  # @@protoc_insertion_point(class_scope:classifier_response)
  })
_sym_db.RegisterMessage(classifier_response)



_DOC_CLASSIFIER_SERVICE = _descriptor.ServiceDescriptor(
  name='doc_classifier_service',
  full_name='doc_classifier_service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=110,
  serialized_end=193,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDocType',
    full_name='doc_classifier_service.GetDocType',
    index=0,
    containing_service=None,
    input_type=_CLASSIFIER_REQUEST,
    output_type=_CLASSIFIER_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOC_CLASSIFIER_SERVICE)

DESCRIPTOR.services_by_name['doc_classifier_service'] = _DOC_CLASSIFIER_SERVICE

# @@protoc_insertion_point(module_scope)
