import grpc

import pb_files.kyc_ocr.autogenerated_files.kyc_ocr_pb2 as kyc_ocr_pb2
import pb_files.kyc_ocr.autogenerated_files.kyc_ocr_pb2_grpc as kyc_ocr_pb2_grpc


def run():
    ocr_channel = grpc.insecure_channel('localhost:50057')
    ocr_stub = kyc_ocr_pb2_grpc.ocr_serviceStub(ocr_channel)
    ocr_response = ocr_stub.GetOcrDetails(kyc_ocr_pb2.kyc_ocr_request(kyc_doc_path='sfkjf/dkd'))



def generateRequests():
    path = '/home/ssg0283/Deskotop/image.jpg'
    return path



if __name__ == '__main__':
    run()